version: '3.3'

services:
  postgres:
    image: postgres:latest
    privileged: true
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    privileged: true
    restart: always
    command: bash -c "
      python app_it_bot.py
      "
    depends_on:
      - postgres
